### PR TITLE
Add action typing (#58)

### LINKED ISSUE #58: Add action typing
I'm looking to get your action first-class supported by https://github.com/krzema12/github-workflows-kt, a Kotlin DSL to write GitHub Action workflows.

They came up with a way to reduce operational load when keeping library's action wrappers in sync with actions' inputs and outputs. The solution includes onboarding https://github.com/krzema12/github-actions-typing. It's as easy as adding an extra YAML file to your repository root, and adding a simple GitHub workflow that validates this new file. Thanks to this, the code generator in the Kotlin DSL can fetch typing info provided by you instead of them, which has a number of benefits. It has no negative effects on current action consumers, they continue to use the action via regular GitHub API, as if the file wasn't there.

In this feature request, I would like to ask you if you're open to introducing such typings in your actions. You wouldn't be first - there's already other actions using it, like e.g. mine: https://github.com/Vampire/setup-wsl

If your answer is "yes", feel free to either add it yourself, or let me know - me or some of the library contributors / maintainers would be happy to post PRs. They're also open to any kind of questions and feedback.

### PR DESCRIPTION
**Pull request by Vampire**
Fixes #58

### CODE REVIEW

**Comment by vlsi** [comment]
Released in v1.15

**Comment by krzema12** [comment]
@vlsi thanks! Could you also update the v1 tag to point to v1.15?

**Comment by vlsi** [comment]
The types are released in v1.16, and v1 should point to v1.16 as well

Is it what you are asking?

**Comment by krzema12** [comment]
Sorry, I meant v1.16, sorry! Please see https://github.com/burrunan/gradle-cache-action/tree/v1, I see some commit from November 2022. Maybe you forgot to push the tag change to the remote?

**Comment by vlsi** [comment]
Sorry for the confusion, now `v1` is properly updated.
However, I assume you would like to see `action-types.yml` on the release branch

**Comment by vlsi** [comment]
I've updated v1 and v1.16: https://github.com/burrunan/gradle-cache-action/tree/v1

**Comment by Vampire** [comment]
Perfect, thanks. :-)

**Pull request merged**
